FROM python:3.12-slim

ENV LANG en_US.UTF-8
ENV LC_ALL en_US.UTF-8

# Run updates
RUN apt-get clean && apt-get update && apt-get upgrade -y && apt-get install -y locales && locale-gen en_US.UTF-8

#Install required python packages 
RUN pip install --no-cache-dir \
    psutil \
    paho-mqtt \
    requests \
    influxdb \
    influxdb-client

COPY grott.py grottconf.py grottdata.py grottproxy.py \
     grottsniffer.py grottserver.py examples/grott.ini \
     examples/Extensions/grottext.py examples/Extensions/grotcsv.py \
     /app/

WORKDIR /app
CMD ["python", "-u", "grott.py", "-v"]
